#!/bin/bash

PY=$(module list 2>&1 >/dev/null | grep -c 'python/2.7')

if [ $PY -lt 1 ]; then
	module load python/2.7
fi

eval "SLURM_Array.py $@"

if [ $PY -lt 1 ]; then
	module unload python/2.7
fi
